### ISSUE TITLE
Error MSG

### ISSUE THREAD

**Issue by chalgoon9** [WooilJeong/CaptchaCracker#4]
import glob
import CaptchaCracker as cc
from tensorflow.python.client import device_lib

target_img_path = 'C:\dev\Ticketing\target_image.png'    #타켓 이미지 경로
img_width = 210 #타켓 이미지 넓이
img_height = 70 #타켓 이미지 높이
max_length = 6  #타켓 이미지가 포함한 문자 수
characters = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'}   #타켓 이미지안에 포함된 문자들
weights_path = 'C:\dev\Ticketing\source\weights.h5' #학습 결과 가중치 경로
AM = cc.ApplyModel(weights_path, img_width, img_height, max_length, characters)   #결과 가중치를 가지는 모델 생성
pred = AM.predict(target_img_path)  #결과 도출
print(pred)

--------------------------------------------
Traceback (most recent call last):
  File "C:\dev\CC\CC.py", line 24, in <module>
    **AM = cc.ApplyModel(weights_path, img_width, img_height, max_length, characters)   #결과 가중치를 가지는 모델 생성**
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\CaptchaCracker\core.py", line 231, in __init__
    self.model.load_weights(weights_path)
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2326, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 713, in load_weights_from_hdf5_group
    backend.batch_set_value(weight_value_tuples)
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\tensorflow\python\keras\backend.py", line 3804, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype_numpy(x)))
  File "C:\Users\SJ\anaconda3\envs\cc5\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 901, in assign
    (tensor_name, self._shape, value_tensor.shape))
**ValueError: Cannot assign to variable dense2/kernel:0 due to variable shape (128, 27) and value shape (128, 19) are incompatible**

-----------------------------------------------
**Tried Python V 3.6 / 3.9
Tried tensorflow with CPU only and CPU & GPU version both,

It worked for learning but not working for prediction**

**Comment by wookidooki8** [comment]
seems like it doesnt recognize alphabets. if you edit characters to have just numbers like characters = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '0'} it works. since they said it works with alphabets, i believe this is supposed to be a bug.

**Comment by chalgoon9** [comment]
> seems like it doesnt recognize alphabet. if you edit characters to have just numbers like characters = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '0'} it works. since they said it works with alphabet, i believe this is supposed to be a bug.

First of all thanks for reply. I am just wondering who is 'they'. You mean Keras? I read your reply in reddit. Alphabet would work as well. Are you willing to figure out this bug?

**Comment by wookidooki8** [comment]
> > seems like it doesnt recognize alphabet. if you edit characters to have just numbers like characters = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '0'} it works. since they said it works with alphabet, i believe this is supposed to be a bug.
> 
> First of all thanks for reply. I am just wondering who is 'they'. You mean Keras? I read your reply in reddit. Alphabet would work as well. Are you willing to figure out this bug?

im not a collaborator but since this module is just a simplified version of [this ](https://keras.io/examples/vision/captcha_ocr/), you might wanna try that.

케라스 웹사이트에 있는 예제 코드를 이용한 모듈이라 케라스에 있는 예제 그대로 이용하시면 작동할겁니당
https://keras.io/examples/vision/captcha_ocr/

**Comment by chalgoon9** [comment]
thanks for your reply and help.

감사합니다.

2022년 10월 8일 (토) 오전 9:58, wookidooki8 ***@***.***>님이 작성:

**Comment by sepanen** [comment]
I have exactly the same problem How to solve this problem?

**Comment by chalgoon9** [comment]
> I have exactly the same problem How to solve this problem?

I have used full Keras module instead of this but using original full keras mudule is much more complicate for captcha solving only. Still hope this project could solve that bug.

**Comment by sepanen** [comment]
> I have used full Keras module instead of this but using original full keras mudule is much more complicate for captcha solving only. Still hope this project could solve that bug.

Thanks for the answer I thought someone had found a solution to the problem in this project to use it in the future
